<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DrugExplorer.Application\DrugExplorer.Application.csproj" />
    <ProjectReference Include="..\DrugExplorer.Infrastructure\DrugExplorer.Infrastructure.csproj" />
    <ProjectReference Include="..\DrugExplorer.Persistence\DrugExplorer.Persistence.csproj" />
  </ItemGroup>

</Project>

